apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::793578691704:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-lwhhuNwI7Juu
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::793578691704:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-01-04T07:07:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1386"
  uid: 654a0f33-2052-464e-988d-9d6121f0a9e8
